package tech.yildirim.camunda.documentmanager.document;

/**
 * Enumeration defining the types of documents that can be stored in the document management system.
 * Used to categorize insurance claim-related documents.
 */
public enum DocumentType {

    /**
     * Customer invoice for repairs, medical treatment, or other claim-related expenses
     */
    INVOICE("Invoice"),

    /**
     * Report generated by the insurance adjuster after claim investigation
     */
    ADJUSTER_REPORT("Adjuster Report");

    private final String displayName;

    /**
     * Constructor for DocumentType enum
     *
     * @param displayName Human-readable display name for the document type
     */
    DocumentType(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Returns the human-readable display name
     *
     * @return Display name of the document type
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Returns the enum constant from a string value (case-insensitive)
     *
     * @param value String representation of the document type
     * @return DocumentType enum constant
     * @throws IllegalArgumentException if the value doesn't match any enum constant
     */
    public static DocumentType fromString(String value) {
        if (value == null || value.trim().isEmpty()) {
            throw new IllegalArgumentException("Document type value cannot be null or empty");
        }

        try {
            return DocumentType.valueOf(value.trim().toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Invalid document type: " + value +
                ". Valid types are: " + java.util.Arrays.toString(DocumentType.values()));
        }
    }
}
